### ISSUE TITLE
please add support for taproot address

### ISSUE THREAD

**Issue by hbasrc** [Perl-Bitcoin/Bitcoin-Crypto#14]
More and more wallets generate P2TR taproot addresses by default,
bitcoin-crypto should prioritize implementing P2TR address generation as well.

**Comment by bbrtj** [comment]
Yes, it's on a list. I understand the importance on it, but it's a big undertaking.

It was impossible to implement without libsecp256k1 ported because there was no decent/secure library for elliptic curve math and schnorr signature generation. It is now possible, but realistically still at least a couple of months away (unless someone contributes).

**Comment by bbrtj** [comment]
Will close this, treating it as a question/feature request. Refer to #6 to track the progress of the implementation - I am keeping that checklist up to date.
